ASkGis.Web.Admin/Controllers/PersonsController.cs
using AskGis.Business;
using AskGis.Entities.InputModels;
using AskGis.Web.Admin.Custom;
using AskGis.Web.Admin.Custom.Attributes;
using AskGis.Web.Admin.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AskGis.Web.Admin.Controllers
{
    public class PersonsController : BaseAdminController
    {
        private readonly IPersonBusiness personBusiness;

        public PersonsController()
        {
            personBusiness = new PersonBusiness();
        }

        public ActionResult Index()
        {
            var viewModel = new PersonIndex_ViewModel
            {
                PageTitle = "Əməkdaşlar",
                Persons = personBusiness.All()
            };

            return View(viewModel);
        }


        public ActionResult Create(int id = 0)
        {
            var person = personBusiness.GetById(id);
            if (id != 0 && person == null)
                throw new Exception("Redaktə edilmək üçün məlumat tapılmadı");

            var viewModel = new PersonCreate_ViewModel
            {
                PageTitle = id == 0 ? "Yeni əməkdaş" : "Əməkdaşın redaktə edilməsi",
                Person = person ?? new Entities.Person()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(PersonSaveInput input)
        {
            if (ModelState.IsValid)
            {
                personBusiness.Save(input);
                return Success(new
                {
                    url = Url.Action("Index")
                });
            }

            var errors = GetModelStateErrors();
            return Failure(new
            {
                message = errors.ElementAt(0)
            });
        }

        public ActionResult Delete(int id)
        {
            var person = personBusiness.GetById(id);
            if (person == null)
                throw new Exception("Silmək üçün məlumat tapılmadı");

            var viewModel = new PersonDelete_ViewModel
            {
                PageTitle = "Əməkdaşın silinməsi",
                Person = person
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        [RequiredPermission("PERSONS_DELETE")]
        public ActionResult DeletePost(int personId)
        {
            personBusiness.Delete(personId);
            return Success();
        }
    }
}

ASkGis.Web.Admin/Controllers/RolesController.cs
using AskGis.Business;
using AskGis.Entities.InputModels;
using AskGis.Web.Admin.Custom;
using AskGis.Web.Admin.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AskGis.Web.Admin.Controllers
{
    public class RolesController : BaseAdminController
    {
        private readonly IRoleBusiness roleBusiness;
        private readonly IPageBusiness pageBusiness;

        public RolesController()
        {
            roleBusiness = new RoleBusiness();
            pageBusiness = new PageBusiness();
        }

        public ActionResult Index()
        {
            var viewModel = new RoleIndex_ViewModel
            {
                PageTitle = "Rollar",
                Roles = roleBusiness.All()
            };
            return View(viewModel);
        }

        public ActionResult Create(int id = 0)
        {
            var role = roleBusiness.GetById(id);
            if (id != 0 && role == null)
                throw new Exception("Rol tapılmadı");

            var viewModel = new RoleCreate_ViewModel
            {
                PageTitle = id == 0 ? "Yeni Rol" : "Rol məlumatlarının redaktə edilməsi",
                PageType = Custom.Enums.PageType.CreateOrEdit,
                Role = role ?? new Entities.Role(),
                Pages = pageBusiness.All(),              
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(RoleSaveInput input)
        {
            if (ModelState.IsValid)
            {
                roleBusiness.Save(input);
                return Success();
            }

            var errors = GetModelStateErrors();
            return Failure(errors.ElementAt(0));
        }

        public ActionResult Delete(int id)
        {
            var role = roleBusiness.GetById(id);
            if (role == null)
                throw new Exception("Rol tapılmadı");
            var viewModel = new RoleCreate_ViewModel
            {
                PageTitle = "Rol məlumatlarının silinməsi",
                Role = role,
                PageType = Custom.Enums.PageType.Delete,
                Pages = pageBusiness.All(),
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            roleBusiness.Delete(id);
            return Success();
        }
    }
}

ASkGis.Web.Admin/Controllers/UsersController.cs
using AskGis.Business;
using AskGis.Entities.InputModels;
using AskGis.Web.Admin.Custom;
using AskGis.Web.Admin.Custom.Enums;
using AskGis.Web.Admin.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AskGis.Web.Admin.Controllers
{
    public class UsersController : BaseAdminController
    {
        private readonly IUserBusiness usersBusiness;
        private readonly IPersonBusiness personsBusiness;
        private readonly IRoleBusiness rolesBusiness;

        public UsersController()
        {
            usersBusiness = new UserBusiness();
            personsBusiness = new PersonBusiness();
            rolesBusiness = new RoleBusiness();
        }

        public ActionResult Index()
        {
            var viewModel = new UsersIndex_ViewModel
            {
                PageTitle = "İstifadəçilər",
                Users = usersBusiness.All()
            };
            return View(viewModel);
        }

        public ActionResult Create(int id = 0)
        {
            var user = usersBusiness.GetById(id);
            if (id != 0 && user == null)
                throw new Exception("İstifadəçi tapılmadı");

            var viewModel = new UsersCreate_ViewModel
            {
                PageTitle = id == 0 ? "Yeni istifadəçi" : "İstifadəçi məlumatlarının redaktə ediilməsi",
                PageType = id == 0 ? PageType.Create : PageType.Edit,
                User = user ?? new Entities.User(),
                PersonsDropDown = personsBusiness.All().Select(p => new SelectListItem
                {
                    Text = $"{p.LastName} {p.FirstName} {p.Fathername}",
                    Value = p.Id.ToString(),
                    Selected = id == 0 ? false : p.Id == user.PersonId
                }),
                RolesDropDown = rolesBusiness.All().Select(p => new SelectListItem
                {
                    Text = p.RoleName,
                    Value = p.Id.ToString(),
                    Selected = id == 0 ? false : p.Id == user.Role.Id
                })
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(NewUserInput input)
        {
            if (ModelState.IsValid)
            {
                usersBusiness.Save(input);
                return Success(new
                {
                    url = Url.Action("Index")
                });
            }

            var errors = GetModelStateErrors();
            return Failure(new
            {
                message = errors.ElementAt(0)
            });
        }

        public ActionResult Delete(int id)
        {
            var user = usersBusiness.GetById(id);
            if (user == null)
                throw new Exception("İstifadəçi tapılmadı");

            var viewModel = new UsersDelete_ViewModel
            {
                PageTitle = "İstifadə məlumatının silinməsi",
                User = user
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            usersBusiness.Delete(id);
            return Success(new
            {
                url = Url.Action("Index")
            });
        }

        public ActionResult ChangePassword(int id)
        {
            var user = usersBusiness.GetById(id);
            if (user == null)
                throw new Exception("İstifadəçi tapılmadı");
            var viewModel = new UsersChangePassword_ViewModel
            {
                PageType = PageType.Edit,
                PageTitle = "İstifadəçi şifrəsinin dəyişdirilməsi",
                User = user
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordInput input)
        {
            if (ModelState.IsValid)
            {
                usersBusiness.ChangePassword(input);
                return Success();
            }

            var errors = GetModelStateErrors();
            return Failure(new
            {
                message = errors.ElementAt(0)
            });
        }
    }
}

ASkGis.Web.Admin/Views/Shared/_ErrorLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Static/vendor/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Static/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Static/vendor/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Static/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Static/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="margin-left:0px;">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">

                <div class="error-page">

                    <div class="error-content">
                        <h3><i class="fa fa-warning text-red"></i>@ViewBag.Title</h3>

                        <p>
                            @RenderBody()
                        </p>
                    </div>
                </div>
                <!-- /.error-page -->

            </section>
            <!-- /.content -->
        </div>
        <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Static/vendor/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Static/vendor//bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Static/vendor/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Static/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Static/js/demo.js"></script>
</body>

</html>

ASkGis.Web.Admin/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Static/vendor/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Static/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Static/vendor/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Static/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Static/css/skins/_all-skins.min.css">

    <link href="~/Static/css/askgis.css" rel="stylesheet" />
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>ASK</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>ASK</b>CİS</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" id="logout-button"><i class="fa fa-eject"></i>&nbsp;&nbsp; Çıxış</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_Menu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Static/vendor/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Static/vendor/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Static/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Bootbox -->
    <script src="~/Static/vendor/bootbox/bootbox.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Static/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Static/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Static/js/demo.js"></script>

    <script src="~/Static/js/askgis.js"></script>
</body>
</html>

ASkGis.Web.Admin/Views/Shared/_Menu.cshtml
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li>
                <a href="@Url.Action("Index", "Persons")">
                    <i class="fa fa-th"></i> <span>Əməkdaşlar</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Roles")">
                    <i class="fa fa-th"></i> <span>Rollar</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Users")">
                    <i class="fa fa-th"></i> <span>İstifadəçilər</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>